@extends('layouts.app')
@php use Illuminate\Support\Str; @endphp
@section('title','Dashboard')
@section('heading','Dashboard')
@section('subheading','Ringkasan aktivitas sekolah hari ini')
@push('head')<style>
.dashboard-page .dashboard-content-animate > *{animation:dashIn .55s cubic-bezier(.2,.75,.25,1) both}
.dashboard-page .dashboard-content-animate > .dashboard-hero{animation-delay:.08s}
.dashboard-page .dashboard-content-animate > .dashboard-stats-row{animation-delay:.18s}
.dashboard-page .dashboard-content-animate > .dashboard-middle-row{animation-delay:.3s}
.dashboard-page .dashboard-content-animate > .dashboard-bottom-row{animation-delay:.42s}
.dashboard-page .dashboard-stats-row .dashboard-stat{animation:dashCard .5s cubic-bezier(.2,.75,.25,1) both}
.dashboard-page .dashboard-stats-row .col-6:nth-child(2) .dashboard-stat{animation-delay:.12s}.dashboard-page .dashboard-stats-row .col-6:nth-child(3) .dashboard-stat{animation-delay:.2s}.dashboard-page .dashboard-stats-row .col-6:nth-child(4) .dashboard-stat{animation-delay:.28s}
@keyframes dashIn{from{opacity:0;transform:translateY(22px)}to{opacity:1;transform:none}}@keyframes dashCard{from{opacity:0;transform:translateY(16px) scale(.97)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.dashboard-page .dashboard-content-animate>* ,.dashboard-page .dashboard-content-animate .dashboard-stat{animation:none!important}}
</style>@endpush
@section('content')
<div class="dashboard-content-animate">
<div class="dashboard-hero mb-4"><div><span class="hero-kicker">{{ now()->translatedFormat('l, d F Y') }}</span><h2>Selamat datang, {{ Str::of(auth()->user()->name)->before(' ') }} 👋</h2><p>Pantau kehadiran siswa dan aktivitas sekolah dari satu tempat.</p></div><div class="hero-clock"><i class="bi bi-clock"></i><strong id="liveClock">--:--</strong><small>Waktu Jakarta</small></div></div>
<div class="row g-3 mb-4 dashboard-stats-row">
 @foreach([['students','Total Siswa','people','blue'],['teachers','Total Guru','person-badge','purple'],['classes','Total Kelas','building','orange'],['hadir','Hadir Hari Ini','check2-circle','green']] as $card)<div class="col-6 col-xl-3"><div class="dashboard-stat"><div class="stat-top"><span class="stat-label">{{$card[1]}}</span><span class="stat-symbol {{$card[3]}}"><i class="bi bi-{{$card[2]}}"></i></span></div><strong class="stat-value">{{$stats[$card[0]]}}</strong><small class="stat-foot"><i class="bi bi-arrow-up-right"></i> Data diperbarui realtime</small></div></div>@endforeach
</div>
<div class="row g-4 mb-4 dashboard-middle-row"><div class="col-xl-8"><div class="panel-card h-100"><div class="panel-head"><div><h5>Tren Kehadiran</h5><small>Aktivitas absensi 7 hari terakhir</small></div><span class="panel-chip"><i class="bi bi-graph-up"></i> Mingguan</span></div><div class="chart-area"><canvas id="attendanceChart"></canvas></div></div></div><div class="col-xl-4"><div class="panel-card h-100"><div class="panel-head"><div><h5>Rekap Hari Ini</h5><small>Distribusi status siswa</small></div></div><div class="attendance-summary">@foreach([['hadir','Hadir','green'],['terlambat','Terlambat','orange'],['izin','Izin','blue'],['sakit','Sakit','red'],['alfa','Alfa','gray']] as $item)<div class="summary-row"><span><i class="summary-dot {{$item[2]}}"></i>{{$item[1]}}</span><strong>{{$stats[$item[0]]}}</strong></div>@endforeach</div><div class="summary-total"><span>Total tercatat</span><strong>{{array_sum(array_intersect_key($stats,array_flip(['hadir','terlambat','izin','sakit','alfa'])))}}</strong></div></div></div></div>
<div class="row g-4 dashboard-bottom-row"><div class="col-xl-8"><div class="panel-card"><div class="panel-head"><div><h5>Aktivitas Terbaru</h5><small>Absensi siswa yang baru dicatat</small></div><a href="{{route('reports.index')}}" class="panel-link">Lihat semua <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table dashboard-table mb-0"><thead><tr><th>Siswa</th><th>Kelas</th><th>Waktu</th><th>Status</th></tr></thead><tbody>@forelse($recent as $a)<tr><td><div class="d-flex align-items-center gap-2"><div class="mini-avatar">{{strtoupper(substr($a->student->name,0,1))}}</div><strong>{{$a->student->name}}</strong></div></td><td><span class="class-pill">{{$a->student->schoolClass->class_name}}</span></td><td class="text-muted">{{$a->check_in_time?:'-'}}</td><td><span class="status-dot {{in_array($a->status,['hadir','terlambat'])?'active':'inactive'}}"><i></i>{{ucfirst($a->status)}}</span></td></tr>@empty<tr><td colspan="4" class="empty">Belum ada aktivitas hari ini.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-4"><div class="panel-card quick-panel"><div class="panel-head"><div><h5>Aksi Cepat</h5><small>Menu yang sering digunakan</small></div></div><a href="{{route('attendance.scan')}}" class="quick-action"><span class="quick-icon blue"><i class="bi bi-qr-code-scan"></i></span><span><strong>Scan Barcode</strong><small>Catat kehadiran dengan QR</small></span><i class="bi bi-chevron-right"></i></a><a href="{{route('attendance.manual')}}" class="quick-action"><span class="quick-icon green"><i class="bi bi-clipboard-check"></i></span><span><strong>Absensi Manual</strong><small>Input status satu kelas</small></span><i class="bi bi-chevron-right"></i></a><a href="{{route('reports.index')}}" class="quick-action"><span class="quick-icon orange"><i class="bi bi-file-earmark-bar-graph"></i></span><span><strong>Buka Laporan</strong><small>Rekap dan export data</small></span><i class="bi bi-chevron-right"></i></a></div></div></div>
</div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script><script>function updateClock(){document.getElementById('liveClock').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}updateClock();setInterval(updateClock,1000);new Chart(document.getElementById('attendanceChart'),{type:'line',data:{labels:['Sen','Sel','Rab','Kam','Jum','Sab','Min'],datasets:[{data:[{{$stats['hadir']}},{{$stats['hadir']}},{{$stats['hadir']}},{{$stats['hadir']}},{{$stats['hadir']}},{{$stats['hadir']}},{{$stats['hadir']}}],borderColor:'#1769db',backgroundColor:'#1769db18',fill:true,tension:.4,pointRadius:4,pointBackgroundColor:'#fff',pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#eef2f7'},ticks:{precision:0}},x:{grid:{display:false}}}}});</script>@endpush
