@extends('layouts.app')
@section('heading','Pengaturan Sekolah')
@section('subheading','Kelola identitas sekolah dan tampilan landing scan barcode')
@section('actions')<a href="{{route('attendance.scan')}}" target="_blank" class="btn btn-outline-primary"><i class="bi bi-box-arrow-up-right me-1"></i> Preview Landing</a>@endsection
@section('content')
<form method="post" enctype="multipart/form-data" action="{{route('settings.save')}}" data-confirm-message="Simpan perubahan identitas dan tampilan landing sekolah?">@csrf
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white border-0 p-4"><h5 class="mb-1">Identitas Sekolah</h5><small class="text-muted">Informasi ini tampil pada portal dan laporan sekolah.</small></div><div class="card-body row g-3 px-4 pb-4">
<div class="col-md-6"><label class="form-label">Nama Sekolah *</label><input class="form-control" name="school_name" value="{{old('school_name',$setting->school_name)}}" required></div><div class="col-md-6"><label class="form-label">Nama Kepala Sekolah</label><input class="form-control" name="principal_name" value="{{old('principal_name',$setting->principal_name)}}"></div><div class="col-md-4"><label class="form-label">Telepon</label><input class="form-control" name="school_phone" value="{{$setting->school_phone}}"></div><div class="col-md-4"><label class="form-label">Email</label><input class="form-control" type="email" name="school_email" value="{{$setting->school_email}}"></div><div class="col-md-4"><label class="form-label">Logo Sekolah</label><input class="form-control" type="file" name="school_logo" accept="image/*"><small class="text-muted">PNG/JPG, maksimal 2 MB.</small></div><div class="col-12"><label class="form-label">Alamat</label><textarea class="form-control" name="school_address" rows="3">{{$setting->school_address}}</textarea></div></div></div>
<div class="card border-0 shadow-sm mb-4" id="landing-settings"><div class="card-header bg-white border-0 p-4 d-flex justify-content-between"><div><h5 class="mb-1">Tampilan Landing Scan</h5><small class="text-muted">Atur halaman scanner yang dibuka wali kelas.</small></div><span class="badge text-bg-primary align-self-start">Landing Page</span></div><div class="card-body px-4 pb-4"><div class="row g-4 align-items-center"><div class="col-lg-5"><label class="form-label fw-semibold">Foto Background Sekolah</label><input class="form-control" type="file" name="landing_background" accept="image/*"><small class="text-muted d-block mt-2">Foto horizontal JPG/PNG, maksimal 4 MB.</small></div><div class="col-lg-7"><div class="rounded-4 overflow-hidden position-relative" style="min-height:210px;background:linear-gradient(120deg,#092c68cc,#1769dbbb){{ $setting->landing_background ? ',url('.asset('storage/'.$setting->landing_background).') center/cover' : '' }}"><div class="position-absolute w-100 h-100 d-flex align-items-end p-4 text-white"><div class="d-flex align-items-center gap-3">@if($setting->school_logo)<img src="{{asset('storage/'.$setting->school_logo)}}" alt="Logo" style="width:58px;height:58px;object-fit:contain;background:white;border-radius:14px;padding:7px">@else<i class="bi bi-mortarboard-fill fs-1"></i>@endif<div><small>Preview Landing</small><h5 class="mb-0">{{$setting->school_name ?: 'Nama Sekolah'}}</h5></div></div></div></div></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white border-0 p-4"><h5 class="mb-1">Akademik & Jam Absensi</h5></div><div class="card-body row g-3 px-4 pb-4"><div class="col-md-3"><label class="form-label">Tahun Ajaran</label><input class="form-control" name="academic_year" value="{{$setting->academic_year}}" required></div><div class="col-md-3"><label class="form-label">Semester</label><select class="form-select" name="semester"><option @selected($setting->semester==='ganjil')>ganjil</option><option @selected($setting->semester==='genap')>genap</option></select></div><div class="col-md-3"><label class="form-label">Jam Masuk</label><input class="form-control" type="time" name="attendance_start_time" value="{{$setting->attendance_start_time}}" required></div><div class="col-md-3"><label class="form-label">Batas Terlambat</label><input class="form-control" type="time" name="late_time_limit" value="{{$setting->late_time_limit}}" required></div></div></div><div class="text-end"><button class="btn btn-primary px-4"><i class="bi bi-check2 me-1"></i> Simpan Pengaturan</button></div></form>
@endsection
