@extends('layouts.app')
@section('title','Kalender')
@section('heading','Kalender')
@section('subheading','Atur tanggal merah dan hari libur sekolah. Hari Minggu otomatis dianggap libur.')
@section('content')
<div class="row g-4">
 <div class="col-12"><div class="alert alert-info border-0 shadow-sm small d-flex justify-content-between align-items-center"><span><i class="bi bi-cloud-check"></i> Sinkronkan daftar hari libur resmi Indonesia berdasarkan tahun yang dipilih.</span><form method="post" action="{{route('holidays.sync')}}" class="ms-3">@csrf<input type="hidden" name="year" value="{{$year}}"><button class="btn btn-sm btn-primary"><i class="bi bi-cloud-download"></i> Sinkronkan Nasional</button></form></div></div>
 <div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-body d-flex justify-content-between align-items-center"><div><h5 class="mb-1">Kalender {{ $year }}</h5><small class="text-muted">Tanggal merah tidak dihitung sebagai hari efektif absensi.</small></div><form class="d-flex gap-2"><select name="year" class="form-select" onchange="this.form.submit()">@for($y=now()->year-2;$y<=now()->year+2;$y++)<option value="{{$y}}" @selected($year===$y)>{{$y}}</option>@endfor</select></form></div></div><div class="calendar-grid mt-3">@for($month=1;$month<=12;$month++)<div class="month-card"><h6>{{\Carbon\Carbon::create($year,$month,1)->translatedFormat('F')}}</h6><div class="week-head"><span>Sn</span><span>Sl</span><span>Rb</span><span>Km</span><span>Jm</span><span>Sa</span><span class="sun">Mg</span></div><div class="days">@php $first=\Carbon\Carbon::create($year,$month,1);$offset=($first->dayOfWeekIso+6)%7;$total=$first->daysInMonth; @endphp @for($i=0;$i<$offset;$i++)<span></span>@endfor @for($day=1;$day<=$total;$day++)@php $date=\Carbon\Carbon::create($year,$month,$day);$holiday=$holidays->first(fn($h)=>$h->holiday_date->isSameDay($date));$isSun=$date->isSunday(); @endphp<span class="day {{($holiday||$isSun)?'holiday':''}} {{ $date->isToday()?'today':'' }}" title="{{$holiday?->name}}">{{$day}}</span>@endfor</div></div>@endfor</div></div>
 <div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold"><i class="bi bi-calendar-plus text-primary"></i> Tambah Hari Libur</div><div class="card-body"><form method="post" action="{{route('holidays.store')}}">@csrf<div class="mb-3"><label class="form-label">Tanggal</label><input type="date" name="holiday_date" class="form-control" required></div><div class="mb-3"><label class="form-label">Nama Hari Libur</label><input name="name" class="form-control" placeholder="Contoh: Hari Kemerdekaan" required></div><div class="mb-3"><label class="form-label">Keterangan</label><textarea name="notes" class="form-control" rows="2"></textarea></div><button class="btn btn-primary w-100">Simpan Hari Libur</button></form></div></div><div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-semibold">Daftar Libur {{ $year }}</div><div class="list-group list-group-flush">@forelse($holidays as $holiday)<div class="list-group-item d-flex justify-content-between align-items-center"><div><strong>{{ $holiday->holiday_date->format('d M') }}</strong><br><small>{{ $holiday->name }}</small></div><form method="post" action="{{route('holidays.destroy',$holiday)}}">@csrf @method('delete')<button class="btn btn-sm btn-light text-danger"><i class="bi bi-trash"></i></button></form></div>@empty<div class="empty">Belum ada hari libur tambahan.</div>@endforelse</div></div></div>
</div>
@endsection
