@extends('layouts.app')
@section('title','Kenaikan Kelas') @section('heading','Kenaikan Kelas')
@section('subheading','Atur siswa naik kelas, tetap, atau lulus')
@section('content')
<div class="card border-0 shadow-sm"><div class="card-body">
<div class="alert alert-info"><i class="bi bi-info-circle"></i> Pilih kelas tujuan untuk siswa yang naik. Pilih <b>Tetap</b> untuk siswa yang tidak naik kelas dan <b>Lulus</b> untuk siswa kelas 6.</div>
<div class="row g-2 mb-3"><div class="col-md-4"><select id="sourceClass" class="form-select"><option value="">Semua kelas asal</option>@foreach($students->pluck('schoolClass')->filter()->unique('id') as $source)<option value="{{ $source->id }}">{{ $source->class_name }} ({{ $source->academic_year }})</option>@endforeach</select></div><div class="col-md-5"><input id="studentSearch" class="form-control" placeholder="Cari nama, NIS, atau NISN..."></div><div class="col-md-3"><button type="button" id="promoteVisible" class="btn btn-outline-primary w-100"><i class="bi bi-arrow-up-circle"></i> Naikkan yang tampil</button></div></div>
<form method="post" action="{{ route('promotions.store') }}">@csrf
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Siswa</th><th>Kelas saat ini</th><th>Keputusan</th></tr></thead><tbody>
@forelse($students as $student)@php($nextClass=$classes->firstWhere('grade_level',($student->schoolClass?->grade_level ?? 0)+1))<tr data-class="{{ $student->class_id }}" data-search="{{ strtolower($student->name.' '.$student->nis.' '.($student->nisn??'')) }}"><td><strong>{{ $student->name }}</strong><small class="d-block text-muted">NIS: {{ $student->nis }}{{ $student->nisn ? ' · NISN: '.$student->nisn : '' }}</small></td><td>{{ $student->schoolClass?->class_name }} <small class="text-muted">({{ $student->schoolClass?->academic_year }})</small></td><td><select class="form-select decision" name="decisions[{{ $student->id }}]"><option value="stay">Tetap / Tidak naik</option><option value="graduate">Lulus</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected($nextClass?->id === $class->id)>Naik ke {{ $class->class_name }} ({{ $class->academic_year }})</option>@endforeach</select></td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">Tidak ada siswa aktif.</td></tr>@endforelse
</tbody></table></div>@if($students->count())<button class="btn btn-primary"><i class="bi bi-save"></i> Simpan Proses Kenaikan</button>@endif</form>
</div></div><script>const source=document.getElementById('sourceClass'),search=document.getElementById('studentSearch'),rows=[...document.querySelectorAll('tbody tr[data-class]')];function filterStudents(){const c=source.value,q=(search.value||'').toLowerCase();rows.forEach(row=>{row.hidden=!!(c&&row.dataset.class!==c)||(q&&!row.dataset.search.includes(q))})}source?.addEventListener('change',filterStudents);search?.addEventListener('input',filterStudents);document.getElementById('promoteVisible')?.addEventListener('click',()=>rows.filter(row=>!row.hidden).forEach(row=>{const select=row.querySelector('.decision');const next=[...select.options].find(option=>option.textContent.trim().startsWith('Naik ke'));if(next)select.value=next.value}));</script>
@endsection
