@extends('layouts.app')
@section('title','Rekap Absensi')
@section('heading','Rekap Absensi')
@section('subheading','Pantau dan unduh riwayat kehadiran siswa')
@section('actions')
<div class="d-flex gap-2"><a class="btn btn-success" href="{{route('reports.excel',request()->query())}}"><i class="bi bi-file-earmark-excel me-1"></i> Excel</a><a class="btn btn-danger" href="{{route('reports.pdf',request()->query())}}"><i class="bi bi-file-earmark-pdf me-1"></i> PDF</a></div>
@endsection
@section('content')
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-lg-4"><form class="row g-3 align-items-end"><div class="col-sm-6 col-lg-2"><label class="form-label small fw-semibold text-muted">Dari tanggal</label><input type="date" name="start_date" value="{{request('start_date')}}" class="form-control"></div><div class="col-sm-6 col-lg-2"><label class="form-label small fw-semibold text-muted">Sampai tanggal</label><input type="date" name="end_date" value="{{request('end_date')}}" class="form-control"></div>@if(!auth()->user()->isWali())<div class="col-sm-6 col-lg-3"><label class="form-label small fw-semibold text-muted">Kelas</label><select name="class_id" class="form-select"><option value="">Semua kelas</option>@foreach($classes as $c)<option value="{{$c->id}}" @selected(request('class_id')==$c->id)>{{$c->class_name}}</option>@endforeach</select></div>@endif<div class="col-sm-6 col-lg-2"><label class="form-label small fw-semibold text-muted">Status</label><select name="status" class="form-select"><option value="">Semua status</option>@foreach(['hadir','terlambat','izin','sakit','alfa'] as $st)<option value="{{$st}}" @selected(request('status')===$st)>{{ucfirst($st)}}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i> Terapkan</button><a class="btn btn-light ms-1" href="{{route('reports.index')}}">Reset</a></div></form></div></div>
<div class="card border-0 shadow-sm overflow-hidden"><div class="card-header bg-white border-0 p-4 d-flex justify-content-between align-items-center"><div><h5 class="mb-1">Data Kehadiran</h5><small class="text-muted">{{$rows->total()}} catatan ditemukan</small></div><span class="badge rounded-pill text-bg-light"><i class="bi bi-clock-history me-1"></i> Terbaru</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Tanggal</th><th>Siswa</th><th>NIS</th><th>Kelas</th><th>Jam</th><th>Status</th><th>Metode</th><th>Petugas</th></tr></thead><tbody>@forelse($rows as $a)<tr><td>{{optional($a->attendance_date)->format('d M Y')}}</td><td class="fw-semibold">{{$a->student->name}}</td><td>{{$a->student->nis}}</td><td><span class="class-pill">{{$a->student->schoolClass->class_name}}</span></td><td>{{$a->check_in_time?:'-'}}</td><td><span class="badge status-{{$a->status}}">{{ucfirst($a->status)}}</span></td><td>{{ucfirst($a->method)}}</td><td>{{$a->recorder->name}}</td></tr>@empty<tr><td colspan="8" class="empty py-5">Belum ada data absensi sesuai filter.</td></tr>@endforelse</tbody></table></div><div class="card-body">{{$rows->links()}}</div></div>
@endsection
