<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
if(!Schema::hasTable('school_settings'))Schema::create('school_settings',function(Blueprint $t){$t->id();$t->string('school_name');$t->text('school_address')->nullable();$t->string('school_phone')->nullable();$t->string('school_email')->nullable();$t->string('principal_name')->nullable();$t->string('school_logo')->nullable();$t->string('academic_year');$t->enum('semester',['ganjil','genap']);$t->time('attendance_start_time')->default('07:00');$t->time('late_time_limit')->default('07:15');$t->string('timezone')->default('Asia/Jakarta');$t->timestamps();});
if(!Schema::hasTable('teachers'))Schema::create('teachers',function(Blueprint $t){$t->id();$t->string('nip')->nullable()->unique();$t->string('name');$t->enum('gender',['L','P']);$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->string('photo')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
if(!Schema::hasTable('school_classes'))Schema::create('school_classes',function(Blueprint $t){$t->id();$t->string('class_name');$t->unsignedTinyInteger('grade_level');$t->string('major')->nullable();$t->foreignId('teacher_id')->nullable()->unique()->constrained('teachers')->nullOnDelete();$t->string('academic_year');$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['class_name','academic_year']);});
if(\Illuminate\Support\Facades\DB::getDriverName()==='sqlite'||!\Illuminate\Support\Facades\DB::table('information_schema.table_constraints')->where('constraint_schema',\Illuminate\Support\Facades\DB::getDatabaseName())->where('table_name','users')->where('constraint_name','users_class_id_foreign')->exists())Schema::table('users',function(Blueprint $t){$t->foreign('class_id')->references('id')->on('school_classes')->nullOnDelete();});
if(!Schema::hasTable('students'))Schema::create('students',function(Blueprint $t){$t->id();$t->string('nis')->unique();$t->string('nisn')->nullable()->unique();$t->string('name');$t->enum('gender',['L','P']);$t->string('birth_place')->nullable();$t->date('birth_date')->nullable();$t->text('address')->nullable();$t->string('parent_name')->nullable();$t->string('parent_phone')->nullable();$t->string('photo')->nullable();$t->foreignId('class_id')->constrained('school_classes')->restrictOnDelete();$t->string('barcode_token',100)->unique();$t->string('barcode_image')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->softDeletes();$t->index(['class_id','is_active']);});
if(!Schema::hasTable('attendances'))Schema::create('attendances',function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->date('attendance_date');$t->time('check_in_time')->nullable();$t->time('check_out_time')->nullable();$t->enum('status',['hadir','terlambat','izin','sakit','alfa']);$t->enum('method',['barcode','manual']);$t->text('notes')->nullable();$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete();$t->string('scanned_token')->nullable();$t->timestamps();$t->unique(['student_id','attendance_date']);$t->index(['attendance_date','status']);});
} public function down():void{Schema::dropIfExists('attendances');Schema::dropIfExists('students');Schema::table('users',fn(Blueprint $t)=>$t->dropForeign(['class_id']));Schema::dropIfExists('school_classes');Schema::dropIfExists('teachers');Schema::dropIfExists('school_settings');}};
