<?php
namespace App\Http\Controllers;
use App\Http\Requests\ScanAttendanceRequest; use App\Models\{Attendance,SchoolClass,SchoolSetting,Student}; use App\Services\AttendanceService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class AttendanceController extends Controller {
 public function studentSearch(Request $r){$term=trim((string)$r->input('q'));$student=null;$summary=null;$history=collect();if($term!==''){$student=Student::with('schoolClass')->where(function($q)use($term){$q->where('barcode_token',$term)->orWhere('nis',$term)->orWhere('nisn',$term)->orWhere('name','like',"%{$term}%");})->first();if($student){$base=$student->attendances()->whereDate('attendance_date','>=',now()->subDays(30));$summary=['total'=>(clone $base)->count(),'hadir'=>(clone $base)->where('status','hadir')->count(),'terlambat'=>(clone $base)->where('status','terlambat')->count(),'izin'=>(clone $base)->whereIn('status',['izin','sakit'])->count()];$history=$student->attendances()->latest('attendance_date')->latest('id')->limit(8)->get();}}return view('admin.student-search',compact('student','summary','history','term'));}
 public function scanPage(){ $user=auth()->user();$classId=$user->isWali()?$user->class_id:null;$query=Attendance::whereDate('attendance_date',today())->when($classId,fn($q)=>$q->whereHas('student',fn($s)=>$s->where('class_id',$classId)));return view('attendances.kiosk',['today'=>(clone $query)->count(),'present'=>(clone $query)->where('status','hadir')->count(),'late'=>(clone $query)->where('status','terlambat')->count(),'school'=>SchoolSetting::first(),'class'=>$user->schoolClass]); }
 public function scan(ScanAttendanceRequest $r,AttendanceService $s){$a=$s->scan($r->token,$r->user())->load('student.schoolClass');return response()->json(['message'=>'Absensi berhasil dicatat.','attendance'=>$a]);}
 public function manual(Request $r){$classId=$r->user()->isWali()?$r->user()->class_id:$r->input('class_id');$date=$r->input('date',today()->toDateString());$students=Student::where('class_id',$classId?:0)->whereDoesntHave('attendances',fn($q)=>$q->whereDate('attendance_date',$date))->orderBy('name')->get();return view('attendances.manual',['students'=>$students,'classes'=>SchoolClass::all(),'classId'=>$classId,'date'=>$date]);}
 public function storeManual(Request $r){$data=$r->validate(['date'=>'required|date','class_id'=>'nullable|exists:school_classes,id','attendances'=>'required|array','attendances.*.status'=>'required|in:hadir,terlambat,izin,sakit,alfa','attendances.*.notes'=>'nullable|string|max:500']);$classId=$r->user()->isWali()?$r->user()->class_id:$data['class_id'];$ids=Student::where('class_id',$classId)->whereIn('id',array_keys($data['attendances']))->pluck('id');DB::transaction(function()use($ids,$data,$r){foreach($ids as $id){$v=$data['attendances'][$id];Attendance::updateOrCreate(['student_id'=>$id,'attendance_date'=>$data['date']],['status'=>$v['status'],'notes'=>$v['notes']??null,'method'=>'manual','recorded_by'=>$r->user()->id,'check_in_time'=>in_array($v['status'],['hadir','terlambat'])?now()->format('H:i:s'):null]);}});return back()->with('success','Absensi manual disimpan.');}
}
